[env:m5stack-cardputer]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed  = 1500000

board_build.partitions = min_spiffs.csv

build_flags =
    -DESP32S3
    -DUSE_AUDIO
    -Wno-narrowing
    -Wno-stringop-overflow
    -DCONFIG_BT_ENABLED=1
    -DNIMBLE_CPP_IDF_VERSION=5
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    ; Cardputer-Adv piny LCD ST7789V2
    -DPIN_LCD_BL=38
    -DPIN_LCD_RST=33
    -DPIN_LCD_DC=34
    -DPIN_LCD_MOSI=35
    -DPIN_LCD_SCK=36
    -DPIN_LCD_CS=37
    ; SD piny
    -DPIN_SD_CS=12
    -DPIN_SD_SCK=40
    -DPIN_SD_MISO=39
    -DPIN_SD_MOSI=14
    ; RFID RC522 (Grove + GPIO)
    -DRFID_CS=1
    -DRFID_RST=2
    ; Bateria ADC
    -DPIN_BAT_ADC=10
    ; IR
    -DIR_TX_PIN=44
    -DIR_RX_PIN=2
    ; GPS UART
    -DGPS_RX_PIN=15
    -DGPS_TX_PIN=13
    ; NRF24L01
    -DNRF24_CE_PIN=16
    -DNRF24_CS_PIN=5
    -DNRF24_SCK=18
    -DNRF24_MOSI=23
    -DNRF24_MISO=19
    ; CC1101
    -DCC1101_SCK=5
    -DCC1101_MISO=19
    -DCC1101_MOSI=23
    -DCC1101_CS=18
    -DCC1101_GDO0=4
    ; FM Si4713 I2C
    -DFM_SDA=21
    -DFM_SCL=22
    ; Flagi NimBLE
    -UCONFIG_BT_NIMBLE_ROLE_CENTRAL
    -UCONFIG_BT_NIMBLE_ROLE_OBSERVER
    -UCONFIG_BT_NIMBLE_ROLE_PERIPHERAL
    -UCONFIG_BT_NIMBLE_ROLE_BROADCASTER

build_unflags =
    -Werror=all

lib_deps =
    ; M5Stack
    m5stack/M5Unified @ ^0.2.2
    m5stack/M5Cardputer @ ^1.0.1
    ; Audio
    earlephilhower/ESP8266Audio @ ^1.9.7
    ; Bluetooth
    h2zero/NimBLE-Arduino @ ^1.4.2
    ; IR
    crankyoldgit/IRremoteESP8266 @ ^2.8.6
    ; RF CC1101
    LSatan/SmartRC-CC1101-Driver-Lib @ ^2.5.7
    ; NRF24L01
    nrf24/RF24 @ ^1.4.8
    ; GPS
    mikalhart/TinyGPSPlus @ ^1.0.3
    ; FM Si4713
    adafruit/Adafruit Si4713 Library @ ^1.2.0
    ; Web/HTTP
    me-no-dev/ESPAsyncWebServer @ ^1.2.4
    me-no-dev/AsyncTCP @ ^1.1.1
    bblanchon/ArduinoJson @ ^7.0.0
    ; RFID RC522
    miguelbalboa/MFRC522 @ ^1.4.11

lib_ldf_mode = deep
